# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: All Package

on:
  push:
    branches:
      - diamodaria

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17.0.12'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2

    - run: gradle shadowJar

    - name: Upload JAR as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-jar
        path: build/libs/*.jar
        retention-days: 4
